# Generated by Django 5.1.6 on 2025-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_cover', models.ImageField(upload_to='album_covers/')),
                ('album_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('favorite_songs', models.TextField()),
                ('rating', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
