# Generated by Django 5.1.6 on 2025-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
